eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/wmdb?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    password: guest
    host: 192.168.3.13
    username: guest
    port: 5672
server:
  port: 9090
