spring:
  application:
    name: product
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wmdb?serverTimezone=UTC
  rabbitmq:
    password: guest
    host: 192.168.3.13
    username: guest
    port: 5672
server:
  port: 8081

