spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/wmdb?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    password: guest
    host: 192.168.3.14
    username: guest
    port: 5672

  redis:
    host: 192.168.3.14
    port: 6379
    
server:
  port: 8686
